### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Oneplus** [Oneplus/tamr#1]
* [ ] alignment for LDC2017T10
* [ ] CCG-AMR alignment hack
* [ ] amr-eager alignment hack
* [ ] CacheTransition-Seq2Seq alignment hack
